# Generated by Django 5.0.4 on 2024-04-26 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='time_valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 8, 1, 22, 423982, tzinfo=datetime.timezone.utc)),
        ),
    ]
