# Generated by Django 5.0.4 on 2024-04-21 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0005_emailconfirm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfirm',
            options={'verbose_name': 'Email Verification', 'verbose_name_plural': 'Email Verifications'},
        ),
        migrations.RemoveField(
            model_name='emailconfirm',
            name='time_created',
        ),
        migrations.AddField(
            model_name='emailconfirm',
            name='time_valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 14, 36, 25, 480566, tzinfo=datetime.timezone.utc)),
        ),
    ]
