# Generated by Django 5.0.4 on 2024-04-22 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0006_alter_emailconfirm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='time_valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 14, 1, 8, 562413, tzinfo=datetime.timezone.utc)),
        ),
    ]
