# Generated by Django 5.0.4 on 2024-04-22 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0009_alter_emailconfirm_time_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='time_valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 14, 15, 16, 878181, tzinfo=datetime.timezone.utc)),
        ),
    ]
