# Generated by Django 5.0.4 on 2024-04-22 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0011_alter_emailconfirm_time_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='time_valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 17, 22, 0, 438464, tzinfo=datetime.timezone.utc)),
        ),
    ]
