# Generated by Django 5.0.4 on 2024-04-23 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0014_alter_emailconfirm_time_valid_treeplantation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='time_valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 21, 12, 21, 770370, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='treeplantation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='treeplantation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
