# Generated by Django 5.0.4 on 2024-04-24 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0018_alter_emailconfirm_time_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='time_valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 1, 25, 5, 453135, tzinfo=datetime.timezone.utc)),
        ),
    ]
