# Generated by Django 5.0.4 on 2024-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplain',
            name='solved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
